url: https://valentinebodywork.com
baseurl: 

# Site settings
title: Valentine Bodywork
email: jenny@valentinebodywork.com
description: "Hello, it's me, your body."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: instagram.com/jennyvalentinecmt

# Build settings
markdown: kramdown
permalink: pretty
